version: '3'
services:
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root@base-backend
      MYSQL_DATABASE: base-backend
      MYSQL_USER: adriennguyen
      MYSQL_PASSWORD: adriennguyen@base
    ports:
      - '3308:3306'
    volumes:
      - ./db:/var/lib/mysql
  redis:
    image: 'redis:alpine'
    restart: always
    command: redis-server
    volumes:
      - ./redis-store:/var/lib/redis
    ports:
      - '6381:6379'
volumes:
  db:
    driver: local
  redis-store:
